  #version of docker-compose#
  version: '3'

  #containers which are being built and run#
  services:
    # container name to be used while creating#
    wedding-frontend:
      image: ezekielbajada/weddinginvite:frontend
      #the path of dockerfile to be used#
      build: .
      #the ports on which the container be mapped onto#
      ports:
        - "80:80"
    wedding-backend:
      image: ezekielbajada/weddinginvite:backend
      #the path of dockerfile to be used#
      build: ../WeddingInviteSiteBackend/WeddingInviteSite
      environment: 
        - ASPNETCORE_URLS=http://+:8081;http://+:5000
      #the ports on which the container be mapped onto#
      ports:
        - "8081:8081"
